### PR TITLE
Pass response body along with error

### PR DESCRIPTION
**Pull request by robkb**
Allow consumers to access any information in the body of the error response.

### CODE REVIEW

**Comment by blakeembrey** [comment]
Maybe it'd be better to link the `request` instance to a `response` instance in `popsicle`? I used to do this before I removed it for no particular reason in some recent releases. Might make sense to add it back. Probably doesn't need to link both ways though, unless you think so.

**Comment by blakeembrey** [comment]
@robert-bosweb How's https://github.com/blakeembrey/popsicle/releases/tag/v8.2.0 for you? 😄 If it works, happy to close this PR.

**Comment by robkb** [comment]
Thanks! The `response.toJSON()` method seems to be missing in 8.2.0? May be something I've done; I'll see if I can work it out.

**Comment by blakeembrey** [comment]
I am seeing it:

image

Did you want to share a snippet of what you're doing?

**Comment by robkb** [comment]
😬 it was me; I had a convenience function that was messing about with the response object before logging it, to cut down on log spam.

**Pull request closed without merging**
